// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Namespace;

#nullable disable

namespace MinimalAPI.Migrations
{
    [DbContext(typeof(AppDataContext))]
    [Migration("20250424172458_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.0");

            modelBuilder.Entity("API.Modelos.Restaurante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Restaurantes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Endereco = "Rua Padre Anchieta, 1287 - Curitiba",
                            Nome = "Terrazza 40",
                            Telefone = "(41) 3014-0141"
                        },
                        new
                        {
                            Id = 2,
                            Endereco = "Av. Silva Jardim, 2487 - Curitiba",
                            Nome = "Barolo Curitiba",
                            Telefone = "(41) 3243-3430"
                        });
                });

            modelBuilder.Entity("Namespace.Prato", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Preco")
                        .HasColumnType("TEXT");

                    b.Property<int?>("RestauranteId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RestauranteId");

                    b.ToTable("Pratos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descricao = "Coxa e sobrecoxa de pato recheadas com miúdos, servidas com purê de batatas, chutney de maçãs e espuma de laranja.",
                            Nome = "Pato de Pomerode",
                            Preco = 79.99m,
                            RestauranteId = 1
                        },
                        new
                        {
                            Id = 2,
                            Descricao = "Barriga de porco confitada, acompanhada de vagens grelhadas e purê de batatas. ",
                            Nome = "Panza de Cerdo",
                            Preco = 99.99m,
                            RestauranteId = 1
                        },
                        new
                        {
                            Id = 3,
                            Descricao = "Robalo coberto com crosta de castanha-de-caju, acompanhado de pappardelle ao molho de ervas e limão-siciliano.",
                            Nome = "Robalo em Crosta de Castanha",
                            Preco = 59.99m,
                            RestauranteId = 2
                        },
                        new
                        {
                            Id = 4,
                            Descricao = "Filé-mignon ao molho de mostarda, servido com ravioloni de queijo, tomate seco e aspargo.",
                            Nome = "Filé ao Molho de Mostarda com Ravioloni",
                            Preco = 119.99m,
                            RestauranteId = 2
                        });
                });

            modelBuilder.Entity("Namespace.Prato", b =>
                {
                    b.HasOne("API.Modelos.Restaurante", "Restaurante")
                        .WithMany()
                        .HasForeignKey("RestauranteId");

                    b.Navigation("Restaurante");
                });
#pragma warning restore 612, 618
        }
    }
}
